// Reference: System.dll
// CompilerOptions: ""

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rhetos.Mvc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Captions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Captions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Captions", typeof(Captions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to log.
        /// </summary>
        public static string Common_AddToLog {
            get {
                return ResourceManager.GetString("Common_AddToLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Common_AddToLog_Action {
            get {
                return ResourceManager.GetString("Common_AddToLog_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Common_AddToLog_Description {
            get {
                return ResourceManager.GetString("Common_AddToLog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item id.
        /// </summary>
        public static string Common_AddToLog_ItemId {
            get {
                return ResourceManager.GetString("Common_AddToLog_ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name.
        /// </summary>
        public static string Common_AddToLog_TableName {
            get {
                return ResourceManager.GetString("Common_AddToLog_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit data modifications.
        /// </summary>
        public static string Common_AuditDataModifications {
            get {
                return ResourceManager.GetString("Common_AuditDataModifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Common_AuditDataModifications_Log {
            get {
                return ResourceManager.GetString("Common_AuditDataModifications_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string Common_AuditDataModifications_Modified {
            get {
                return ResourceManager.GetString("Common_AuditDataModifications_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New value.
        /// </summary>
        public static string Common_AuditDataModifications_NewValue {
            get {
                return ResourceManager.GetString("Common_AuditDataModifications_NewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old value.
        /// </summary>
        public static string Common_AuditDataModifications_OldValue {
            get {
                return ResourceManager.GetString("Common_AuditDataModifications_OldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string Common_AuditDataModifications_Property {
            get {
                return ResourceManager.GetString("Common_AuditDataModifications_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit related events.
        /// </summary>
        public static string Common_AuditRelatedEvents {
            get {
                return ResourceManager.GetString("Common_AuditRelatedEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Common_AuditRelatedEvents_Action {
            get {
                return ResourceManager.GetString("Common_AuditRelatedEvents_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client user name.
        /// </summary>
        public static string Common_AuditRelatedEvents_ClientUserName {
            get {
                return ResourceManager.GetString("Common_AuditRelatedEvents_ClientUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client workstation.
        /// </summary>
        public static string Common_AuditRelatedEvents_ClientWorkstation {
            get {
                return ResourceManager.GetString("Common_AuditRelatedEvents_ClientWorkstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Common_AuditRelatedEvents_Created {
            get {
                return ResourceManager.GetString("Common_AuditRelatedEvents_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Common_AuditRelatedEvents_Description {
            get {
                return ResourceManager.GetString("Common_AuditRelatedEvents_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item id.
        /// </summary>
        public static string Common_AuditRelatedEvents_ItemId {
            get {
                return ResourceManager.GetString("Common_AuditRelatedEvents_ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Common_AuditRelatedEvents_Log {
            get {
                return ResourceManager.GetString("Common_AuditRelatedEvents_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation.
        /// </summary>
        public static string Common_AuditRelatedEvents_Relation {
            get {
                return ResourceManager.GetString("Common_AuditRelatedEvents_Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Common_AuditRelatedEvents_Summary {
            get {
                return ResourceManager.GetString("Common_AuditRelatedEvents_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name.
        /// </summary>
        public static string Common_AuditRelatedEvents_TableName {
            get {
                return ResourceManager.GetString("Common_AuditRelatedEvents_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto code cache.
        /// </summary>
        public static string Common_AutoCodeCache {
            get {
                return ResourceManager.GetString("Common_AutoCodeCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity.
        /// </summary>
        public static string Common_AutoCodeCache_Entity {
            get {
                return ResourceManager.GetString("Common_AutoCodeCache_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        public static string Common_AutoCodeCache_Grouping {
            get {
                return ResourceManager.GetString("Common_AutoCodeCache_Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last code.
        /// </summary>
        public static string Common_AutoCodeCache_LastCode {
            get {
                return ResourceManager.GetString("Common_AutoCodeCache_LastCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min digits.
        /// </summary>
        public static string Common_AutoCodeCache_MinDigits {
            get {
                return ResourceManager.GetString("Common_AutoCodeCache_MinDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string Common_AutoCodeCache_Prefix {
            get {
                return ResourceManager.GetString("Common_AutoCodeCache_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string Common_AutoCodeCache_Property {
            get {
                return ResourceManager.GetString("Common_AutoCodeCache_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim.
        /// </summary>
        public static string Common_Claim {
            get {
                return ResourceManager.GetString("Common_Claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivan.
        /// </summary>
        public static string Common_Claim_Active {
            get {
                return ResourceManager.GetString("Common_Claim_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim resource.
        /// </summary>
        public static string Common_Claim_ClaimResource {
            get {
                return ResourceManager.GetString("Common_Claim_ClaimResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim right.
        /// </summary>
        public static string Common_Claim_ClaimRight {
            get {
                return ResourceManager.GetString("Common_Claim_ClaimRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted items.
        /// </summary>
        public static string Common_DeletedItems {
            get {
                return ResourceManager.GetString("Common_DeletedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name.
        /// </summary>
        public static string Common_DeletedItems_TableName {
            get {
                return ResourceManager.GetString("Common_DeletedItems_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive lock.
        /// </summary>
        public static string Common_ExclusiveLock {
            get {
                return ResourceManager.GetString("Common_ExclusiveLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock finish.
        /// </summary>
        public static string Common_ExclusiveLock_LockFinish {
            get {
                return ResourceManager.GetString("Common_ExclusiveLock_LockFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock start.
        /// </summary>
        public static string Common_ExclusiveLock_LockStart {
            get {
                return ResourceManager.GetString("Common_ExclusiveLock_LockStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource i d.
        /// </summary>
        public static string Common_ExclusiveLock_ResourceID {
            get {
                return ResourceManager.GetString("Common_ExclusiveLock_ResourceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource type.
        /// </summary>
        public static string Common_ExclusiveLock_ResourceType {
            get {
                return ResourceManager.GetString("Common_ExclusiveLock_ResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Common_ExclusiveLock_UserName {
            get {
                return ResourceManager.GetString("Common_ExclusiveLock_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workstation.
        /// </summary>
        public static string Common_ExclusiveLock_Workstation {
            get {
                return ResourceManager.GetString("Common_ExclusiveLock_Workstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter id.
        /// </summary>
        public static string Common_FilterId {
            get {
                return ResourceManager.GetString("Common_FilterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle.
        /// </summary>
        public static string Common_FilterId_Handle {
            get {
                return ResourceManager.GetString("Common_FilterId_Handle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Common_FilterId_Value {
            get {
                return ResourceManager.GetString("Common_FilterId_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep synchronized metadata.
        /// </summary>
        public static string Common_KeepSynchronizedMetadata {
            get {
                return ResourceManager.GetString("Common_KeepSynchronizedMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        public static string Common_KeepSynchronizedMetadata_Context {
            get {
                return ResourceManager.GetString("Common_KeepSynchronizedMetadata_Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Common_KeepSynchronizedMetadata_Source {
            get {
                return ResourceManager.GetString("Common_KeepSynchronizedMetadata_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Common_KeepSynchronizedMetadata_Target {
            get {
                return ResourceManager.GetString("Common_KeepSynchronizedMetadata_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Common_Log {
            get {
                return ResourceManager.GetString("Common_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Common_Log_Action {
            get {
                return ResourceManager.GetString("Common_Log_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context info.
        /// </summary>
        public static string Common_Log_ContextInfo {
            get {
                return ResourceManager.GetString("Common_Log_ContextInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Common_Log_Created {
            get {
                return ResourceManager.GetString("Common_Log_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Common_Log_Description {
            get {
                return ResourceManager.GetString("Common_Log_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item id.
        /// </summary>
        public static string Common_Log_ItemId {
            get {
                return ResourceManager.GetString("Common_Log_ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name.
        /// </summary>
        public static string Common_Log_TableName {
            get {
                return ResourceManager.GetString("Common_Log_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Common_Log_UserName {
            get {
                return ResourceManager.GetString("Common_Log_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workstation.
        /// </summary>
        public static string Common_Log_Workstation {
            get {
                return ResourceManager.GetString("Common_Log_Workstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log entry.
        /// </summary>
        public static string Common_LogEntry {
            get {
                return ResourceManager.GetString("Common_LogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log i d.
        /// </summary>
        public static string Common_LogEntry_LogID {
            get {
                return ResourceManager.GetString("Common_LogEntry_LogID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged item.
        /// </summary>
        public static string Common_LoggedItem {
            get {
                return ResourceManager.GetString("Common_LoggedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item id.
        /// </summary>
        public static string Common_LoggedItem_ItemId {
            get {
                return ResourceManager.GetString("Common_LoggedItem_ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name.
        /// </summary>
        public static string Common_LoggedItem_TableName {
            get {
                return ResourceManager.GetString("Common_LoggedItem_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log reader.
        /// </summary>
        public static string Common_LogReader {
            get {
                return ResourceManager.GetString("Common_LogReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Common_LogReader_Action {
            get {
                return ResourceManager.GetString("Common_LogReader_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context info.
        /// </summary>
        public static string Common_LogReader_ContextInfo {
            get {
                return ResourceManager.GetString("Common_LogReader_ContextInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Common_LogReader_Created {
            get {
                return ResourceManager.GetString("Common_LogReader_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Common_LogReader_Description {
            get {
                return ResourceManager.GetString("Common_LogReader_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item id.
        /// </summary>
        public static string Common_LogReader_ItemId {
            get {
                return ResourceManager.GetString("Common_LogReader_ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name.
        /// </summary>
        public static string Common_LogReader_TableName {
            get {
                return ResourceManager.GetString("Common_LogReader_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Common_LogReader_UserName {
            get {
                return ResourceManager.GetString("Common_LogReader_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workstation.
        /// </summary>
        public static string Common_LogReader_Workstation {
            get {
                return ResourceManager.GetString("Common_LogReader_Workstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log related item.
        /// </summary>
        public static string Common_LogRelatedItem {
            get {
                return ResourceManager.GetString("Common_LogRelatedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item id.
        /// </summary>
        public static string Common_LogRelatedItem_ItemId {
            get {
                return ResourceManager.GetString("Common_LogRelatedItem_ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Common_LogRelatedItem_Log {
            get {
                return ResourceManager.GetString("Common_LogRelatedItem_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation.
        /// </summary>
        public static string Common_LogRelatedItem_Relation {
            get {
                return ResourceManager.GetString("Common_LogRelatedItem_Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name.
        /// </summary>
        public static string Common_LogRelatedItem_TableName {
            get {
                return ResourceManager.GetString("Common_LogRelatedItem_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log related item reader.
        /// </summary>
        public static string Common_LogRelatedItemReader {
            get {
                return ResourceManager.GetString("Common_LogRelatedItemReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item id.
        /// </summary>
        public static string Common_LogRelatedItemReader_ItemId {
            get {
                return ResourceManager.GetString("Common_LogRelatedItemReader_ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Common_LogRelatedItemReader_Log {
            get {
                return ResourceManager.GetString("Common_LogRelatedItemReader_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation.
        /// </summary>
        public static string Common_LogRelatedItemReader_Relation {
            get {
                return ResourceManager.GetString("Common_LogRelatedItemReader_Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name.
        /// </summary>
        public static string Common_LogRelatedItemReader_TableName {
            get {
                return ResourceManager.GetString("Common_LogRelatedItemReader_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My claim.
        /// </summary>
        public static string Common_MyClaim {
            get {
                return ResourceManager.GetString("Common_MyClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies.
        /// </summary>
        public static string Common_MyClaim_Applies {
            get {
                return ResourceManager.GetString("Common_MyClaim_Applies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string Common_Principal {
            get {
                return ResourceManager.GetString("Common_Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Common_Principal_Name {
            get {
                return ResourceManager.GetString("Common_Principal_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal has role.
        /// </summary>
        public static string Common_PrincipalHasRole {
            get {
                return ResourceManager.GetString("Common_PrincipalHasRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string Common_PrincipalHasRole_Principal {
            get {
                return ResourceManager.GetString("Common_PrincipalHasRole_Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Common_PrincipalHasRole_Role {
            get {
                return ResourceManager.GetString("Common_PrincipalHasRole_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal permission.
        /// </summary>
        public static string Common_PrincipalPermission {
            get {
                return ResourceManager.GetString("Common_PrincipalPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim.
        /// </summary>
        public static string Common_PrincipalPermission_Claim {
            get {
                return ResourceManager.GetString("Common_PrincipalPermission_Claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is authorized.
        /// </summary>
        public static string Common_PrincipalPermission_IsAuthorized {
            get {
                return ResourceManager.GetString("Common_PrincipalPermission_IsAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string Common_PrincipalPermission_Principal {
            get {
                return ResourceManager.GetString("Common_PrincipalPermission_Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related events source.
        /// </summary>
        public static string Common_RelatedEventsSource {
            get {
                return ResourceManager.GetString("Common_RelatedEventsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Common_RelatedEventsSource_Action {
            get {
                return ResourceManager.GetString("Common_RelatedEventsSource_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context info.
        /// </summary>
        public static string Common_RelatedEventsSource_ContextInfo {
            get {
                return ResourceManager.GetString("Common_RelatedEventsSource_ContextInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Common_RelatedEventsSource_Created {
            get {
                return ResourceManager.GetString("Common_RelatedEventsSource_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Common_RelatedEventsSource_Description {
            get {
                return ResourceManager.GetString("Common_RelatedEventsSource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item id.
        /// </summary>
        public static string Common_RelatedEventsSource_ItemId {
            get {
                return ResourceManager.GetString("Common_RelatedEventsSource_ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Common_RelatedEventsSource_Log {
            get {
                return ResourceManager.GetString("Common_RelatedEventsSource_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related to item.
        /// </summary>
        public static string Common_RelatedEventsSource_RelatedToItem {
            get {
                return ResourceManager.GetString("Common_RelatedEventsSource_RelatedToItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related to table.
        /// </summary>
        public static string Common_RelatedEventsSource_RelatedToTable {
            get {
                return ResourceManager.GetString("Common_RelatedEventsSource_RelatedToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation.
        /// </summary>
        public static string Common_RelatedEventsSource_Relation {
            get {
                return ResourceManager.GetString("Common_RelatedEventsSource_Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name.
        /// </summary>
        public static string Common_RelatedEventsSource_TableName {
            get {
                return ResourceManager.GetString("Common_RelatedEventsSource_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Common_RelatedEventsSource_UserName {
            get {
                return ResourceManager.GetString("Common_RelatedEventsSource_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workstation.
        /// </summary>
        public static string Common_RelatedEventsSource_Workstation {
            get {
                return ResourceManager.GetString("Common_RelatedEventsSource_Workstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release lock.
        /// </summary>
        public static string Common_ReleaseLock {
            get {
                return ResourceManager.GetString("Common_ReleaseLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource i d.
        /// </summary>
        public static string Common_ReleaseLock_ResourceID {
            get {
                return ResourceManager.GetString("Common_ReleaseLock_ResourceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource type.
        /// </summary>
        public static string Common_ReleaseLock_ResourceType {
            get {
                return ResourceManager.GetString("Common_ReleaseLock_ResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report template.
        /// </summary>
        public static string Common_ReportTemplate {
            get {
                return ResourceManager.GetString("Common_ReportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Common_ReportTemplate_Content {
            get {
                return ResourceManager.GetString("Common_ReportTemplate_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string Common_ReportTemplate_DisplayName {
            get {
                return ResourceManager.GetString("Common_ReportTemplate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string Common_ReportTemplate_FileName {
            get {
                return ResourceManager.GetString("Common_ReportTemplate_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Common_Role {
            get {
                return ResourceManager.GetString("Common_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Common_Role_Name {
            get {
                return ResourceManager.GetString("Common_Role_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role inherits role.
        /// </summary>
        public static string Common_RoleInheritsRole {
            get {
                return ResourceManager.GetString("Common_RoleInheritsRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions from.
        /// </summary>
        public static string Common_RoleInheritsRole_PermissionsFrom {
            get {
                return ResourceManager.GetString("Common_RoleInheritsRole_PermissionsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users from.
        /// </summary>
        public static string Common_RoleInheritsRole_UsersFrom {
            get {
                return ResourceManager.GetString("Common_RoleInheritsRole_UsersFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role permission.
        /// </summary>
        public static string Common_RolePermission {
            get {
                return ResourceManager.GetString("Common_RolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim.
        /// </summary>
        public static string Common_RolePermission_Claim {
            get {
                return ResourceManager.GetString("Common_RolePermission_Claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is authorized.
        /// </summary>
        public static string Common_RolePermission_IsAuthorized {
            get {
                return ResourceManager.GetString("Common_RolePermission_IsAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Common_RolePermission_Role {
            get {
                return ResourceManager.GetString("Common_RolePermission_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row permissions read items.
        /// </summary>
        public static string Common_RowPermissionsReadItems {
            get {
                return ResourceManager.GetString("Common_RowPermissionsReadItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row permissions write items.
        /// </summary>
        public static string Common_RowPermissionsWriteItems {
            get {
                return ResourceManager.GetString("Common_RowPermissionsWriteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set lock.
        /// </summary>
        public static string Common_SetLock {
            get {
                return ResourceManager.GetString("Common_SetLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource i d.
        /// </summary>
        public static string Common_SetLock_ResourceID {
            get {
                return ResourceManager.GetString("Common_SetLock_ResourceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource type.
        /// </summary>
        public static string Common_SetLock_ResourceType {
            get {
                return ResourceManager.GetString("Common_SetLock_ResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System required active.
        /// </summary>
        public static string Common_SystemRequiredActive {
            get {
                return ResourceManager.GetString("Common_SystemRequiredActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System required claim.
        /// </summary>
        public static string Common_SystemRequiredClaim {
            get {
                return ResourceManager.GetString("Common_SystemRequiredClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System required log.
        /// </summary>
        public static string Common_SystemRequiredLog {
            get {
                return ResourceManager.GetString("Common_SystemRequiredLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System required principal.
        /// </summary>
        public static string Common_SystemRequiredPrincipal {
            get {
                return ResourceManager.GetString("Common_SystemRequiredPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System required role.
        /// </summary>
        public static string Common_SystemRequiredRole {
            get {
                return ResourceManager.GetString("Common_SystemRequiredRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System required users from.
        /// </summary>
        public static string Common_SystemRequiredUsersFrom {
            get {
                return ResourceManager.GetString("Common_SystemRequiredUsersFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Stanovnik_Adresa {
            get {
                return ResourceManager.GetString("Stanovnik_Adresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa u gradu.
        /// </summary>
        public static string Stanovnik_Adresa_AdresaUGradu {
            get {
                return ResourceManager.GetString("Stanovnik_Adresa_AdresaUGradu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kucni broj.
        /// </summary>
        public static string Stanovnik_Adresa_KucniBroj {
            get {
                return ResourceManager.GetString("Stanovnik_Adresa_KucniBroj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string Stanovnik_Adresa_Naziv {
            get {
                return ResourceManager.GetString("Stanovnik_Adresa_Naziv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra.
        /// </summary>
        public static string Stanovnik_Adresa_Sifra {
            get {
                return ResourceManager.GetString("Stanovnik_Adresa_Sifra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država.
        /// </summary>
        public static string Stanovnik_Drzava {
            get {
                return ResourceManager.GetString("Stanovnik_Drzava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string Stanovnik_Drzava_Naziv {
            get {
                return ResourceManager.GetString("Stanovnik_Drzava_Naziv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra.
        /// </summary>
        public static string Stanovnik_Drzava_Sifra {
            get {
                return ResourceManager.GetString("Stanovnik_Drzava_Sifra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        public static string Stanovnik_Grad {
            get {
                return ResourceManager.GetString("Stanovnik_Grad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad u državi.
        /// </summary>
        public static string Stanovnik_Grad_GradUDrzavi {
            get {
                return ResourceManager.GetString("Stanovnik_Grad_GradUDrzavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        public static string Stanovnik_Grad_Naziv {
            get {
                return ResourceManager.GetString("Stanovnik_Grad_Naziv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postanski broj.
        /// </summary>
        public static string Stanovnik_Grad_PostanskiBroj {
            get {
                return ResourceManager.GetString("Stanovnik_Grad_PostanskiBroj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra.
        /// </summary>
        public static string Stanovnik_Grad_Sifra {
            get {
                return ResourceManager.GetString("Stanovnik_Grad_Sifra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoba.
        /// </summary>
        public static string Stanovnik_Osoba {
            get {
                return ResourceManager.GetString("Stanovnik_Osoba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string Stanovnik_Osoba_Ime {
            get {
                return ResourceManager.GetString("Stanovnik_Osoba_Ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OIB.
        /// </summary>
        public static string Stanovnik_Osoba_OIB {
            get {
                return ResourceManager.GetString("Stanovnik_Osoba_OIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string Stanovnik_Osoba_Prezime {
            get {
                return ResourceManager.GetString("Stanovnik_Osoba_Prezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System required šifra.
        /// </summary>
        public static string Stanovnik_SystemRequiredSifra {
            get {
                return ResourceManager.GetString("Stanovnik_SystemRequiredSifra", resourceCulture);
            }
        }
    }
}
